from generator.constants import BASE_DIR, FONTS_DIR


DEFAULT_ALT_TEXT_FILENAME = "AlternativeMenuNames.json"
DEFAULT_FONT_FILENAME = "BPreplayBold-unhinted.otf"
DEFAULT_FONT_PATH = FONTS_DIR / DEFAULT_FONT_FILENAME
DEFAULT_THEME_DIR = "Generated Theme"
DEFAULT_THEME_PATH = BASE_DIR / DEFAULT_THEME_DIR
